struct Solution {
    length: u32,
    color: String,
}

fn solve(input: Vec<&str>) -> Solution {
    let mut previous_color = "";
    let mut current_color = "";
    let mut length = 0;
    let mut longest = Solution {
        length,
        color: String::from(current_color),
    };

    input.iter().for_each(|color| {
        if previous_color.is_empty() && current_color.is_empty() {
            current_color = color;
            length += 1;
        } else if !current_color.is_empty() && previous_color.is_empty() {
            if color != &current_color {
                previous_color = current_color;
                current_color = color;
                length += 1;
            }
        } else if color != &previous_color && color == &current_color {
            if length >= longest.length {
                longest = Solution {
                    length,
                    color: String::from(current_color),
                };
            }
            current_color = color;
            previous_color = "";
            length = 1;
        } else if color != &previous_color && color != &current_color {
            if length >= longest.length {
                longest = Solution {
                    length,
                    color: String::from(current_color),
                }
            };
            previous_color = current_color;
            current_color = color;
            length = 2;
        } else {
            previous_color = current_color;
            current_color = color;
            length += 1;
        }
    });

    if length >= longest.length {
        longest = Solution {
            length,
            color: String::from(current_color),
        };
    }

    longest
}

fn main() {
    let data = vec![
        "red", "blue", "green", "gray", "blue", "red", "blue", "blue", "red", "red", "green",
        "gray", "green", "red", "green", "red", "green", "red", "green", "red", "green", "red",
        "green", "red", "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue", "gray", "blue",
        "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray",
        "green", "gray", "red", "red", "red", "green", "blue", "red", "green", "blue", "blue",
        "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "red", "gray", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "red", "blue", "green",
        "gray", "blue", "red", "blue", "blue", "red", "red", "green", "gray", "green", "red",
        "green", "red", "green", "red", "green", "red", "green", "red", "green", "red", "green",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "gray", "green", "blue", "gray", "blue", "gray", "green", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "green", "gray", "green", "gray", "red",
        "red", "red", "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "red", "green",
        "green", "red", "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue",
        "red", "red", "green", "gray", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "red", "green", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue",
        "gray", "blue", "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "gray", "green", "gray", "red", "red", "red", "green", "blue", "red",
        "green", "blue", "blue", "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "red", "gray",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "red", "green", "green", "red", "green", "red", "blue",
        "green", "gray", "blue", "red", "blue", "blue", "red", "red", "green", "gray", "green",
        "red", "green", "red", "green", "red", "green", "red", "green", "red", "green", "red",
        "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "gray", "green", "blue", "gray", "blue", "gray", "green", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray", "green", "gray",
        "red", "red", "red", "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "red", "green",
        "green", "red", "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue",
        "red", "red", "green", "gray", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "red", "green", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue",
        "gray", "blue", "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "gray", "green", "gray", "red", "red", "red", "green", "blue", "red",
        "green", "blue", "blue", "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "red", "gray",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "red", "green", "green", "red", "green", "red", "blue",
        "green", "gray", "blue", "red", "blue", "blue", "red", "red", "green", "gray", "green",
        "red", "green", "red", "green", "red", "green", "red", "green", "red", "green", "red",
        "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "gray", "green", "blue", "gray", "blue", "gray", "green", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray", "green", "gray",
        "red", "red", "red", "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "red", "blue", "green", "gray", "blue",
        "red", "blue", "blue", "red", "red", "green", "gray", "green", "red", "green", "red",
        "green", "red", "green", "red", "green", "red", "green", "red", "green", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "gray", "green", "blue", "gray", "blue", "gray", "green", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "gray", "green", "gray", "red", "red", "red",
        "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "red", "green", "green", "red",
        "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue", "red", "red",
        "green", "gray", "green", "red", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue", "gray", "blue",
        "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray",
        "green", "gray", "red", "red", "red", "green", "blue", "red", "green", "blue", "blue",
        "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "red", "gray", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "red", "green", "green", "red", "green", "red", "blue", "green", "gray", "blue",
        "red", "blue", "blue", "red", "red", "green", "gray", "green", "red", "green", "red",
        "green", "red", "green", "red", "green", "red", "green", "red", "green", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "gray", "green", "blue", "gray", "blue", "gray", "green", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "gray", "green", "gray", "red", "red", "red",
        "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "red", "green", "green", "red",
        "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue", "red", "red",
        "green", "gray", "green", "red", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue", "gray", "blue",
        "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray",
        "green", "gray", "red", "red", "red", "green", "blue", "red", "green", "blue", "blue",
        "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "red", "gray", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "red", "green", "green", "red", "green", "red", "blue", "green", "gray", "blue",
        "red", "blue", "blue", "red", "red", "green", "gray", "green", "red", "green", "red",
        "green", "red", "green", "red", "green", "red", "green", "red", "green", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "gray", "green", "blue", "gray", "blue", "gray", "green", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "gray", "green", "gray", "red", "red", "red",
        "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "red", "blue", "green", "gray", "blue", "red", "blue", "blue",
        "red", "red", "green", "gray", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "red", "green", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue",
        "gray", "blue", "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "gray", "green", "gray", "red", "red", "red", "green", "blue", "red",
        "green", "blue", "blue", "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "red", "gray",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "red", "green", "green", "red", "green", "red", "blue",
        "green", "gray", "blue", "red", "blue", "blue", "red", "red", "green", "gray", "green",
        "red", "green", "red", "green", "red", "green", "red", "green", "red", "green", "red",
        "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "gray", "green", "blue", "gray", "blue", "gray", "green", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray", "green", "gray",
        "red", "red", "red", "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "red", "green",
        "green", "red", "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue",
        "red", "red", "green", "gray", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "red", "green", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue",
        "gray", "blue", "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "gray", "green", "gray", "red", "red", "red", "green", "blue", "red",
        "green", "blue", "blue", "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "red", "gray",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "red", "green", "green", "red", "green", "red", "blue",
        "green", "gray", "blue", "red", "blue", "blue", "red", "red", "green", "gray", "green",
        "red", "green", "red", "green", "red", "green", "red", "green", "red", "green", "red",
        "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "gray", "green", "blue", "gray", "blue", "gray", "green", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray", "green", "gray",
        "red", "red", "red", "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "red", "green",
        "green", "red", "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue",
        "red", "red", "green", "gray", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "red", "green", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue",
        "gray", "blue", "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "gray", "green", "gray", "red", "red", "red", "green", "blue", "red",
        "green", "blue", "blue", "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "red", "gray",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "red", "blue", "green", "gray", "blue", "red", "blue", "blue", "red", "red", "green",
        "gray", "green", "red", "green", "red", "green", "red", "green", "red", "green", "red",
        "green", "red", "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue", "gray", "blue",
        "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray",
        "green", "gray", "red", "red", "red", "green", "blue", "red", "green", "blue", "blue",
        "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "red", "gray", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "red", "green", "green", "red", "green", "red", "blue", "green", "gray", "blue",
        "red", "blue", "blue", "red", "red", "green", "gray", "green", "red", "green", "red",
        "green", "red", "green", "red", "green", "red", "green", "red", "green", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "gray", "green", "blue", "gray", "blue", "gray", "green", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "gray", "green", "gray", "red", "red", "red",
        "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "red", "green", "green", "red",
        "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue", "red", "red",
        "green", "gray", "green", "red", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue", "gray", "blue",
        "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray",
        "green", "gray", "red", "red", "red", "green", "blue", "red", "green", "blue", "blue",
        "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "red", "gray", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "red", "green", "green", "red", "green", "red", "blue", "green", "gray", "blue",
        "red", "blue", "blue", "red", "red", "green", "gray", "green", "red", "green", "red",
        "green", "red", "green", "red", "green", "red", "green", "red", "green", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "gray", "green", "blue", "gray", "blue", "gray", "green", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "gray", "green", "gray", "red", "red", "red",
        "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "red", "green", "green", "red",
        "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue", "red", "red",
        "green", "gray", "green", "red", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue", "gray", "blue",
        "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray",
        "green", "gray", "red", "red", "red", "green", "blue", "red", "green", "blue", "blue",
        "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "red", "gray", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "red", "blue", "green",
        "gray", "blue", "red", "blue", "blue", "red", "red", "green", "gray", "green", "red",
        "green", "red", "green", "red", "green", "red", "green", "red", "green", "red", "green",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "gray", "green", "blue", "gray", "blue", "gray", "green", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "green", "gray", "green", "gray", "red",
        "red", "red", "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "red", "green",
        "green", "red", "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue",
        "red", "red", "green", "gray", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "red", "green", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue",
        "gray", "blue", "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "gray", "green", "gray", "red", "red", "red", "green", "blue", "red",
        "green", "blue", "blue", "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "red", "gray",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "red", "green", "green", "red", "green", "red", "blue",
        "green", "gray", "blue", "red", "blue", "blue", "red", "red", "green", "gray", "green",
        "red", "green", "red", "green", "red", "green", "red", "green", "red", "green", "red",
        "green", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "gray", "green", "blue", "gray", "blue", "gray", "green", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "green", "gray", "green", "gray",
        "red", "red", "red", "green", "blue", "red", "green", "blue", "blue", "red", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "red", "gray", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "red", "green",
        "green", "red", "green", "red", "blue", "green", "gray", "blue", "red", "blue", "blue",
        "red", "red", "green", "gray", "green", "red", "green", "red", "green", "red", "green",
        "red", "green", "red", "green", "red", "green", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "gray", "green", "blue",
        "gray", "blue", "gray", "green", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "green", "gray", "green", "gray", "red", "red", "red", "green", "blue", "red",
        "green", "blue", "blue", "red", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue",
        "red", "blue", "red", "blue", "green", "red", "green", "red", "green", "green", "red",
        "green", "red", "green", "green", "red", "green", "red", "green", "green", "red", "green",
        "red", "green", "green", "red", "green", "red", "green", "green", "red", "green", "red",
        "green", "green", "red", "green", "red", "green", "green", "red", "green", "red", "green",
        "green", "red", "green", "red", "green", "green", "red", "green", "red", "green", "green",
        "red", "green", "red", "green", "green", "red", "green", "red", "green", "red", "gray",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red", "blue", "red",
        "blue", "red", "blue", "red", "red", "green", "green", "red", "green", "pink",
    ];
    let result = solve(data);
    println!("{}@{}", result.length, result.color);
}

#[cfg(test)]
mod tests {
    #[test]
    fn solve_test_1() {
        let result = super::solve(vec!["red", "blue", "red", "blue", "green"]);
        assert_eq!(result.length, 4);
        assert_eq!(result.color, String::from("blue"));
    }

    #[test]
    fn solve_test_2() {
        let result = super::solve(vec!["green", "red", "blue", "gray"]);
        assert_eq!(result.length, 2);
        assert_eq!(result.color, String::from("gray"));
    }

    #[test]
    fn solve_test_3() {
        let result = super::solve(vec!["blue", "blue", "blue", "blue"]);
        assert_eq!(result.length, 1);
        assert_eq!(result.color, String::from("blue"));
    }

    #[test]
    fn solve_test_4() {
        let result = super::solve(vec!["red", "green", "red", "green", "red", "green"]);
        assert_eq!(result.length, 6);
        assert_eq!(result.color, String::from("green"));
    }

    #[test]
    fn solve_test_5() {
        let result = super::solve(vec!["blue", "red", "blue", "red", "gray"]);
        assert_eq!(result.length, 4);
        assert_eq!(result.color, String::from("red"));
    }

    #[test]
    fn solve_test_6() {
        let result = super::solve(vec!["red", "red", "blue", "red", "red", "red", "green"]);
        assert_eq!(result.length, 3);
        assert_eq!(result.color, String::from("red"));
    }

    #[test]
    fn solve_test_7() {
        let result = super::solve(vec![
            "red", "blue", "red", "green", "red", "green", "red", "green",
        ]);
        assert_eq!(result.length, 6);
        assert_eq!(result.color, String::from("green"));
    }
}
